title: AquaBalance
logo: /assets/img/logo.png
description: AquaBalance is an iOS app that records, tracks and reminds users to drink water.
show_downloads: false
#google_analytics: [Google Analytics tracking ID]
theme: jekyll-theme-minimal
# Usage at https://github.com/pages-themes/minimal

